package com.jjhsoftware.memoryversechallenge.bible;

import java.util.ArrayList;

import com.jjhsoftware.memoryversechallenge.models.Verse;

/**
 * Created by JHESE154 on 8/24/2016.
 * A class that holds the Bible verses to be shown on the user
 */
public class BibleV1 {
    public final static ArrayList<Verse> versesQuery = new ArrayList<Verse>();
    public static final int VERSE_COUNT = 32 ;  // hardcoded for optimization. Fix this everytime
    public static final double VERSION = 1.0;  // support for future updates

    public static ArrayList<Verse> generateQuery() {
        // JSON
        versesQuery.add(new Verse(0, "Romans 3:23", "For all have sinned and fall short of the glory of God.", "Sapagkat ang lahat ay nagkasala at walang sinumang karapat-dapat sa paningin ng Diyos."));
        versesQuery.add(new Verse(1, "Romans 6:23", "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", "Sapagkat kamatayan ang kabayaran ng kasalanan, ngunit ang kaloob ng Diyos ay buhay na walang hanggan sa pamamagitan ni Cristo Jesus na ating Panginoon."));
        versesQuery.add(new Verse(2, "Romans 5:8", "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.", "Ngunit ipinadama ng Diyos ang kanyang pag-ibig sa atin nang mamatay si Cristo para sa atin noong tayo’y makasalanan pa."));
        versesQuery.add(new Verse(3, "Ephesians 2:8-9 ", "For it is by grace you have been saved, through faith – and this not from yourselves, it is the gift of God – not by works, so that no one can boast.", "Dahil sa kagandahang-loob ng Diyos ay naligtas kayo sa pamamagitan ng inyong pananalig kay Cristo. At ang kaligtasang ito'y kaloob ng Diyos, hindi mula sa inyo. Hindi ito dahil sa inyong mga gawa kaya't walang dapat ipagmalaki ang sinuman."));
        versesQuery.add(new Verse(4, "John 1:12-13 ", "Yet to all who received him, to those who believed in his name, he gave the right to become children of God – children born not of natural descent, nor of human decision or a husband’s will, but born of God.", "Ngunit ang lahat ng tumanggap at nanalig sa Kanya ay pinagkalooban niya ng karapatang maging anak ng Diyos. Sila nga’y naging anak ng Diyos, hindi dahil sa isinilang sila ayon sa kalikasan, ni sa pita ng laman o sa kagagawan ng tao. Ang pagiging anak nila ay buhat sa Diyos."));
        versesQuery.add(new Verse(5, "1 John 5:13", "I write these things to you who believe in the name of the Son of God so that you may know that you have eternal life.", "Isinusulat ko ito sa inyo upang malaman ninyo na kayong nananalig sa Anak ng Diyos ay may buhay na walang hanggan."));
        versesQuery.add(new Verse(6, "2 Peter 3:18", "But grow in the grace and knowledge of our Lord and Savior Jesus Christ. To him be glory both now and forever! Amen.", "Ayon sa kagandahang-loob ng Diyos, magpatuloy kayo sa paglago sa kabutihan at sa pagkakilala sa ating Panginoon at Tagapagligtas na si Jesu- Cristo.  Sa kanya ang kapurihan, ngayon at magpakailanman! Amen"));
        versesQuery.add(new Verse(7, "1 Peter 2:2", "Like newborn babies, crave pure spiritual milk, so that by it you may grow up in your salvation.", "Gaya ng sanggol, kayo’y manabik sa gatas na espirituwal upang umunlad sa pananampalataya hanggang kamtan ang ganap na kaligtasan. "));
        versesQuery.add(new Verse(8, "Joshua 1:8", "Do not let this book of the law depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful.", "Huwag mong kaliligtaang basahin ang aklat na yaon. Dili-dilihin mo iyon araw-gabi upang matupad mo ang lahat ng nasusulat doon. Sa gayon, giginhawa ka at magtatagumpay."));
        versesQuery.add(new Verse(9, "John 15:7", "If you remain in me and my words remain in you, ask whatever you wish, and it will be given you.", "Kung nananatili kayo sa akin at nananatili sa inyo ang mga salita ko, hingin ninyo ang inyong maibigan at ipagkakaloob sa inyo."));
        versesQuery.add(new Verse(10, "Philippians 4:6-7", "Do not be anxious about anything, but in everything by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", "Huwag kayong mabalisa tungkol sa anumang bagay. Sa halip ay hingin ninyo sa Diyos ang lahat ng inyong kailangan sa pamamagitan ng panalanging may pasasalamat. At ang di-malirip na kapayapaan ng Diyos ang mag-iingat sa inyong puso at pag-iisip sa pamamagitan ni Cristo Jesus."));
        versesQuery.add(new Verse(11, "Hebrews 10:24-25", "And let us consider how we may spur one another on toward love and good deeds. Let us not give up meeting together, as some are in the habit of doing, but let us encourage one another – and all the more as you see the Day approaching.", "At sikapin nating mapukaw ang damdamin ng bawat isa sa pag-ibig sa kapwa, at sapaggawa ng mabuti. At huwag kaligtaan ang pagdalo sa ating mga pagtitipon gaya ng ginawa ng ilan, kundi palakasin ang loob ng isa’t-isa, lalo na ngayong nakikita nating nalalapit na ang pagdating ng Panginoon."));
        versesQuery.add(new Verse(12, "Matthew 6:33", "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", "Ngunit pagsumakitan ninyo nang higit sa lahat ang pagharian kayo ng Diyos at mamuhay nang ayon sa kanyang kalooban, at ipagkakaloob niya ang lahat ng kailangan ninyo."));
        versesQuery.add(new Verse(13, "Romans 12:2", "Do not conform any longer to the patterns of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God’s will is – his good, pleasing and perfect will.", "Huwag kayong umayon sa takbo ng mundong ito. Mag-iba na kayo at magbago ng isip upang mabatid ninyo ang kalooban ng Diyos – kung ano ang mabuti, nakalulugod sa kanya, at talagang ganap."));
        versesQuery.add(new Verse(14, "Matthew 16:24-25", "Then Jesus said to his disciples, “If anyone would come after me, he must deny himself and take up his cross and follow me. 25 For whoever wants to save his life will lose it, but whoever loses his life for me will find it.", "Sinabi ni Jesus sa kanyang mga alagad, “Kung ibig ninumang sumunod sa akin, limutin niya ang ukol sa kanyang sarili, pasanin ang kanyang krus at sumunod sa akin. 25 Ang naghahangad na magligtas ng kanyang buhay ay siyang mawawalan nito; ngunit ang mag-alay nito ng kanyang buhay alang-alang sa akin ay siyang "));
        versesQuery.add(new Verse(15, "1 Corinthians 15:58", "Therefore, my dear brothers, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.", "Kaya nga, mga kapatid, magpakatatag kayo at huwag matitinag. Magpakasipag kayo sa gawain para sa Panginoon yamang alam ninyong di nasasayang ang inyong pagpapagal para sa kanya."));
        versesQuery.add(new Verse(16, "Mark 10:45", "For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.", "Sapagkat ang Anak ng Tao ay naparito, hindi upang paglingkuran kundi upang maglingkod at ibigay ang kanyang buhay na ikatutubos ng marami."));
        versesQuery.add(new Verse(17, "Proverbs 3:9-10", "Honor the Lord with your wealth, with the first fruits of all your crops; then your barns will be filled to overflowing, and your vats will brim over with new wine. ", "Si Yahweh ay handugan mo, bahagi ng kayamanan, pinakamainam na ani mo, sa kanya ay ibigay. 10 Sa gayon, kamalig mo ay lagi nang aapaw, sisidlan ng inumin ay hindi nga matutuyuan. "));
        versesQuery.add(new Verse(18, "Acts 1:8", "But you will receive power when the Holy Spirit comes on you; and You will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.", "Ngunit bibigyan kayo ng kapangyarihan pagbaba sa inyo ng Espiritu Santo, at kayo’y magiging mga saksi ko sa Jerusalem, sa buong Judea at Samaria, at hanggang sa dulo ng daigdig.”"));
        versesQuery.add(new Verse(19, "1 Corinthians 2:12 ", "We have not received the spirit of the world but the Spirit who is from God, that we may understand what God has freely given us.", "Hindi ang espiritu ng sanlibutan kundi ang Espiritu ng Diyos ang tinanggap natin upang ating maunawaan ang mga kaloob niya sa atin."));
        versesQuery.add(new Verse(20, "Philippians 4:13", "I can do everything through him who gives me strength.", "Ang lahat ng ito’y magagawa ko dahil sa lakas na kaloob sa akin ni Cristo."));
        versesQuery.add(new Verse(21, "Lamentations 3:22-23", "Because of the Lord’s great love we are not consumed, for his compassions never fail. 23 They are new every morning; great is your faithfulness. ", "Ang hindi nagmamaliw na pag-ibig ni Yahweh at ang kanyang walang kupas na kahabagan, 23 hindi nagbabago tulad ng bukang-liwayway, dakila ang kanyang katapatan. "));
        versesQuery.add(new Verse(22, "1 Peter 5:7", "Cast all your anxiety on him because he cares for you.", "Ipagkatiwala ninyo sa kanya ang inyong mga kabalisahan sapagkat siya ang kumukupkop sa inyo."));
        versesQuery.add(new Verse(23, "Philippians 4:19", "And my God will meet all your needs according to his glorious riches in Christ Jesus.", "At buhat sa kayamanan niyang hindi mauubos, ibibigay niya ang lahat ng inyong kailangan sa pamamagitan ni Cristo Jesus."));
        versesQuery.add(new Verse(24, "1 Corinthians 10:13", "No temptation has seized you except what is common to man. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can stand up under it.", "Wala pang pagsubok na dumating sa inyo na di dinanas ng lahat ng tao. Tapa tang Diyos, at hindi niya ipahihintulot na kayo’y subukin ng higit sa inyong makakaya. Sa halip, pagdating ng pagsubok, bibigyan niya kayo ng lakas upang mapagtagumpayan iyon."));
        versesQuery.add(new Verse(25, "Hebrews 12:2", "Let us fix our eyes on Jesus, the author and perfecter of our faith, who for the joy set before him endured the cross, scorning its shame, and sat down at the right hand of the throne of God.", "Ituon natin ang ating paningin kay Jesus na siyang pinagmulan ng ating pananampalataya, at siya ring nagpapasakdal nito. Dahil sa kagalakang naghihintay sa kanya, hindi niya ikinahiya ang mamatay sa krus, at siya ngayo’y nakaluklok sa kanan ng trono ng Diyos."));
        versesQuery.add(new Verse(26, "John 13:34-35", "A new command I give you: Love one another. As I have loved you, so you must love one another. By this all men will know that you are my disciples, if you love one another.", "Isang bagong utos ang binibigay ko sa inyo: mag-ibigan kayo! Kung paanong inibig ko kayo, gayon din naman, mag-ibigan kayo0. 35 Kung kayo’y mag-ibigan, makikilala ng lahat na kayo’y mga alagad ko."));
        versesQuery.add(new Verse(27, "Philippians 2:3-5", "Do nothing out of selfish ambition or vain conceit, but in humility consider others better than yourselves. 4 Each of you should look not only to your own interests, but also to the interests of others. 5 Your attitude should be the same as that of Christ Jesus.", "Huwag kayong gagawa ng anumang bagay dahil lamang sa hangad ninyong matanyag, bagkus magpakababa kayo at huwag ipalagay na kayo’y mabuti kaysa iba. 4 Ipagmalasakit ninyo ang kapakanan ng iba, hindi lamang ang sa inyong sarili. 5 Magpakababa kayo tulad ni Cristo Jesus."));
        versesQuery.add(new Verse(28, "1 Peter 2:11", "Dear friends, I urge you, as aliens and strangers in the world, to abstain from sinful desires, which war against your soul.", "Mga pinakamamahal, ipinamamanhik ko sa inyo, bilang mga dayuhang nakikipamayan sa daigdig na ito, talikdan na ninyo ang masasamang hilig ng katawan na naghihimagsik laban sa espiritu."));
        versesQuery.add(new Verse(29, "Acts 24:16", "So I strive always to keep my conscience clear before God and man.", "Kaya’t pinagsisikapan ko tuwina na maging malinis ang aking budhi sa harapan ng Diyos at ng tao."));
        versesQuery.add(new Verse(30, "Galatians 6:9-10", "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. 10 Therefore, as we have opportunity, let us do good to all people, especially to those who belong to the family of believers.", "Kaya’t huwag tayong magsawa sa paggawa ng mabuti; pagdating ng takdang panahon, tayo’y mag-aani kung hindi tayo magsa-sawa. 10 Samantalahin natin ang lahat ng pagkakataon sa paggawa ng mabuti sa ating kapwa, lalo na sa mga kapatid sa pananampalataya."));
        versesQuery.add(new Verse(31, "Romans 12:1", "Therefore, I urge you, brothers, in view of God's mercy, to offer your bodies as living sacrifices, holy and pleasing to God – this is your spiritual act of worship.", "Kaya nga, mga kapatid, alang-alang sa masaganang habag ng Diyos sa atin, ako'y namamanhik sa inyo: ialay ninyo ang inyong sarili bilang handog na buhay, banal at kalugud- lugod sa kanya. Ito ang karapat-dapat na pagsamba ninyo sa Diyos."));

        return versesQuery;
    }
}
